### ISSUE TITLE
Question about using the mock for development purposes

### ISSUE THREAD

**Issue by designmatters** [Informatievlaanderen/MAGDA-Mock#1]
I'm trying to build a docker image for the purpose of experimenting with calling the mocked Persoon webservice. Is there any documentation on doing this?

**Comment by laurensdeb** [comment]
You can pull the Docker image from the Github container registry. More documentation in the form of a few tutorials will follow with the next release of the mock.

https://github.com/Informatievlaanderen/MAGDA-Mock/pkgs/container/magda-mock

For reference: [How to authenticate with the Github container registry.](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) 

Best regards,

Laurens Debackere
— Solution Architect MAGDA Mock

**Comment by designmatters** [comment]
Thanks for the info Laurens, I managed to pull it and get a result.

`curl -L 'http://localhost:8080/api/Magda-02.00/soap/WebService' \
-H 'Content-Type: text/xml' \
-d '....'
