### ISSUE TITLE
GeefHistoriekPersoon HistoriekAfstammingDalendeLijn

### ISSUE THREAD

**Issue by MarOngVl** [Informatievlaanderen/MAGDA-Mock#2]
Hi,

For the development of my project, I need to retrieve the data HistoriekAfstammingDalendeLijn from the service GeefHistoriekPersoon. While I was validating my mocked xml response based on the most recent GeefHistoriekPersoonResponse.xsd, the following error was thrown.

![image](https://github.com/Informatievlaanderen/MAGDA-Mock/assets/145711825/98c1c2a2-7bff-4c3d-a97c-e348f469a984)

HistoriekAfstammingDalendeLijn does not appear in the expected values, so my guess is that this data is not supported.

Can you provide me any information on this issue? 

Thanks in advance,

Marnix

**Comment by laurensdeb** [comment]
This appears to be an issue in the validation of the xs:sequence. There is a specific order which needs to be respected in the elements of HistoriekPersoonType.

i.e. HistoriekReferentiepersoon needs to come after HistoriekAfstammingDalendeLijn.

Could you reorder the elements of your response such that HistoriekAfstammingDalendeLijn comes before HistoriekRegerentiepersoon?
